spring.application.name=Question-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/QuizApplicationQuestionDB
spring.datasource.username = postgres
spring.datasource.password=Dhanu999

server.port=8090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.property.hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect