spring.application.name=AuthService

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/QuizApplicationAuthDB
spring.datasource.username = postgres
spring.datasource.password= Dhanu999

server.port=8088

spring.jpa.hibernate.ddl-auto=update
spring.jpa.property.hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect
management.endpoints.web.exposure.include=*

app.jwt.secret = RabtcZoJO1U8nzn3_Gw6u6_apHt_123d
app.jwt.expiration = 86400000

spring.main.web-application-type=servlet
