spring.application.name=question-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/QuizApplicationQuestionDB
spring.datasource.username = postgres
spring.datasource.password= Dhanu999

spring.jpa.hibernate.ddl-auto=update
spring.jpa.property.hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect
management.endpoints.web.exposure.include=*

gateway.secret = gTw!3s7x8@APIOnly

#spring.boot.admin.client.url=http://localhost:9090
spring.boot.admin.client.enabled=true
management.endpoint.health.show-details=always
