spring.application.name=API-gateway

server.port=8765
spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.discovery.locator.lower-case-service-id=true
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true

app.jwt.secret = RabtcZoJO1U8nzn3_Gw6u6_apHt_123d
app.jwt.expiration = 86400000

# Eureka Discovery Client Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#spring.main.web-application-type=reactive
#
#logging.level.org.springframework.cloud.gateway=DEBUG
#logging.level.com.dhanashri.API_gateway.Security=DEBUG





